### ISSUE TITLE
FE-Admin-Ruta /usuarios contiene tabla, boton y form para editar usuario con dropdown para actualizar rol

### ISSUE THREAD

**Issue by victor013001** [victor013001/IW-Proyecto-3#11]
- La tabla muestra el id, fecha, correo y rol de los usuarios.
- El botón muestra un dialog con un form. El form tiene un dropdown para seleccionar un usuario, un dropdown para seleccionar el rol y botones de aceptar o descartar.
- El dropdown de usuarios muestra los correos
- El dropdown de rol tiene las opciones de ADMIN y USER
- Descartar cierra el dialog
- Aceptar modifica el rol de un usuario.
- Se muestra un toast de fallo si la respuesta del BE es un null o un toast de exito en caso contrario.
- El dialog se cierra y limpia si el cambio se realizó de forma exitosa en caso contrario queda abierto sin limpiar el form.

**Comment by mateoalvmad** [comment]
**⛔️La tabla muestra el id, fecha, correo y rol de los usuarios:** Falta mostrarlos desde la BDD.
**⛔️El botón muestra un dialog con un form:** Falta cargar los usuarios desde la BDD.
**⛔️El dropdown de usuarios muestra los correos:** Falta cargar los correos desde la BDD.
**✅El dropdown de rol tiene las opciones de ADMIN y USER**
**✅Descartar cierra el dialog**
**⚠️Aceptar modifica el rol de un usuario:** Pendiente.
**⚠️Se muestra un toast de fallo si la respuesta del BE es un null o un toast de éxito en caso contrario:** Pendiente.
**⚠️El dialog se cierra y limpia si el cambio se realizó de forma exitosa en caso contrario queda abierto sin limpiar el form:** Pendiente.

**Comment by mateoalvmad** [comment]
**✅La tabla muestra el id, fecha, correo y rol de los usuarios.
✅El botón muestra un dialog con un form: Falta cargar los usuarios desde la BDD.
✅El dropdown de usuarios muestra los correos: Falta cargar los correos desde la BDD.
✅El dropdown de rol tiene las opciones de ADMIN y USER.
✅Descartar cierra el dialog.
✅Aceptar modifica el rol de un usuario.
✅Se muestra un toast de fallo si la respuesta del BE es un null o un toast de éxito en caso contrario.
✅El dialog se cierra y limpia si el cambio se realizó de forma exitosa en caso contrario queda abierto sin limpiar el form.**

**Comment by mateoalvmad** [comment]
- Se puede hacer un reload apenas actualice el rol del usuario para que se muestre actualizado en la página?
- Lo del acceso a la página de usario solo por el ADMIN ya está hecho?
